# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: muse life
description: > # this means to ignore newlines until "baseurl:"
  A random blog about topics from math, computer science, physics, to philosophy
  that are considered interesting at the time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://muse.life" # the base hostname & protocol for your site
github_username:  amarmaduke
twitter_username: numbergames

# Build settings
markdown: kramdown

# Exclusions
exclude: [visualizations]

plugins_dir: _plugins

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: ['all']
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# ALGOLIA_API_KEY='{your_admin_api_key}' bundle exec jekyll algolia
algolia:
  application_id: 'JZCK1C4OJG'
  index_name: 'blog'
  search_only_api_key: 'f605571707bbbd81f7b73056d605b2a9'